Update lint.yaml bloquer le push si y a des erreurs

diff --git a/.github/workflows/lint.yaml b/.github/workflows/lint.yaml
--- a/.github/workflows/lint.yaml
+++ b/.github/workflows/lint.yaml
@@ -3,7 +3,7 @@ name: ESLint Check
 on:
   push:
     branches:
-      - main # Déclenchez le workflow lorsque des modifications sont poussées sur la branche principale (changez-la selon vos besoins)
+      - main
 
 jobs:
   lint:
@@ -16,10 +16,18 @@ jobs:
       - name: Setup Node.js
         uses: actions/setup-node@v2
         with:
-          node-version: 16 # Choisissez la version de Node.js dont vous avez besoin
+          node-version: 16
 
       - name: Install Dependencies
-        run: npm --force install # Assurez-vous d'installer ESLint et toutes les dépendances nécessaires
+        run: npm --force install
 
       - name: Run ESLint
-        run: npm run lint # Assurez-vous que vous avez une commande de lint configurée dans votre projet
+        run: npm run lint
+        continue-on-error: true # Continue même en cas d'erreur
+
+      - name: Check ESLint Status
+        run: |
+          if [ ${{ job.status }} != "completed" ]; then
+            echo "ESLint check failed. Cancelling the workflow..."
+            exit 1
+          fi
